# Generated by Django 4.1 on 2023-03-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRAND',
            fields=[
                ('brd_id', models.AutoField(primary_key=True, serialize=False)),
                ('brd_name', models.CharField(max_length=100)),
                ('brd_description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254, unique=True)),
                ('econtact', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_date', models.DateField()),
                ('ord_status', models.IntegerField()),
                ('add_id', models.CharField(max_length=500)),
                ('total', models.CharField(max_length=10)),
                ('payment_status', models.IntegerField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('pd_name', models.CharField(max_length=100)),
                ('pd_img', models.CharField(max_length=100)),
                ('pd_img1', models.CharField(max_length=100, null=True)),
                ('pd_img2', models.CharField(max_length=100, null=True)),
                ('pd_img3', models.CharField(max_length=100, null=True)),
                ('pd_img4', models.CharField(max_length=100, null=True)),
                ('pd_description', models.CharField(max_length=1000)),
                ('pd_price', models.FloatField(max_length=7)),
                ('pd_qty', models.CharField(max_length=10)),
                ('brd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.brand')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField()),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WISHLISTS',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_date', models.DateField(max_length=10)),
                ('pd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.users')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='SUBCATEGORY',
            fields=[
                ('scat_id', models.AutoField(primary_key=True, serialize=False)),
                ('scat_name', models.CharField(max_length=30)),
                ('scat_description', models.CharField(max_length=500)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='scat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.subcategory'),
        ),
        migrations.CreateModel(
            name='ORDER_ITEM',
            fields=[
                ('ord_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=500)),
                ('oi_amt', models.CharField(max_length=100)),
                ('ord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.order')),
                ('pd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.users'),
        ),
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('pd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.product')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='FEEDBACK',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_description', models.CharField(max_length=1000)),
                ('feed_date', models.DateField()),
                ('pd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.users')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='CART',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('pd_qty', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('added_date', models.DateField()),
                ('pd_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='igadmin.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='igadmin.users')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='ADDRESSES',
            fields=[
                ('add_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=50)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igadmin.users')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
