# Generated by Django 4.1 on 2023-03-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igadmin', '0002_product_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
    ]
