# Generated by Django 4.1 on 2023-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igadmin', '0003_remove_product_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
