# Generated by Django 4.1 on 2023-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igadmin', '0005_alter_contact_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_email',
            field=models.CharField(max_length=35),
        ),
    ]
